### ISSUE TITLE
Copy mongodb files with "croc *"

### ISSUE THREAD

**Issue by muhazzz** [schollz/croc#204]
croc version v8.0.3-03fe1c7

Trying to copy mongodb files from one host to another with "croc *". Some files copied, but then get errors:
```
...
index-1321--6693747212794873778.wt      100% |████████████████████| (41.2 MB/s) [0s:0s] ✔️
index-1323--6693747212794873778.wt      100% |████████████████████| (4.9 MB/s) [0s:0s] ✔️
index-1324--6693747212794873778.wt      100% |████████████████████| (4.1 MB/s) [0s:0s] ✔️
index-1325--6693747212794873778.wt      100% |████████████████████| (1.9 MB/s) [0s:0s] ✔️
index-1326--6693747212794873778.wt      100% |████████████████████| (4.1 MB/s) [0s:0s] ✔️
index-1328--6693747212794873778.wt      100% |████████████████████| (29.6 MB/s) [0s:0s] ✔️
index-1329--6693747212794873778.wt      100% |████████████████████| (26.9 MB/s) [0s:0s] ✔️
index-1330--6693747212794873778.wt      100% |████████████████████| (23.1 MB/s) [0s:0s] ✔️
index-1332--6693747212794873778.wt      100% |████████████████████| (23.7 MB/s) [0s:0s] ✔️
index-1333--6693747212794873778.wt      100% |████████████████████| (25.9 MB/s) [0s:0s] ✔️
index-1334--6693747212794873778.wt      100% |████████████████████| (35.9 MB/s) [0s:0s] ✔️
index-1--5864970783244983927.wt         100% |████████████████████| (26.7 MB/s) [0s:0s] ✔️
fatal error: concurrent map read and map write

goroutine 1231 [running]:
runtime.throw(0x88abba, 0x21)
	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc000249ec8 sp=0xc000249e98 pc=0x432aa2
runtime.mapaccess2_fast64(0x809d00, 0xc0004001e0, 0x10000, 0x8000, 0x10000)
	/usr/local/go/src/runtime/map_fast64.go:61 +0x1a5 fp=0xc000249ef0 sp=0xc000249ec8 pc=0x4111d5
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc000082780, 0x2)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1200 +0x598 fp=0xc000251fd0 sp=0xc000249ef0 pc=0x7445a8
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000251fd8 sp=0xc000251fd0 pc=0x461b61
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1079 +0x34e

goroutine 1 [chan receive, 5 minutes]:
github.com/schollz/croc/v8/src/croc.(*Client).Send(0xc000082780, 0xc00017c000, 0x1cb, 0x200, 0x1, 0x88366b, 0x13)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:399 +0x2df
github.com/schollz/croc/v8/src/cli.send(0xc0000b0b00, 0x0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:217 +0x76d
github.com/schollz/croc/v8/src/cli.Run.func4(0xc0000b0b00, 0x0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:97 +0x18f
github.com/urfave/cli.HandleAction(0x7f4900, 0x89c6f8, 0xc0000b0b00, 0x0, 0x0)
	/home/zns/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:523 +0x11a
github.com/urfave/cli.(*App).Run(0xc00015e000, 0xc0000c0000, 0x1b6, 0x200, 0x0, 0x0)
	/home/zns/go/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:285 +0x63d
github.com/schollz/croc/v8/src/cli.Run(0xbaeba0, 0xc00003a778)
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:103 +0xb32
main.main()
	/home/zns/go/src/github.com/schollz/croc/main.go:17 +0x22

goroutine 7 [IO wait, 5 minutes]:
internal/poll.runtime_pollWait(0x7f5885d5be38, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc00040c018, 0x72, 0x0, 0x0, 0x87be32)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc00040c000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc00040c000, 0xc000406dd0, 0x91b9c0, 0xc0000b6040)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000410000, 0xc000410000, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000410000, 0x3, 0x8778f6, 0x1, 0x91a580)
	/usr/local/go/src/net/tcpsock.go:261 +0x64
github.com/schollz/croc/v8/src/tcp.(*server).run(0xc000518000, 0x0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/tcp/tcp.go:95 +0x289
github.com/schollz/croc/v8/src/tcp.(*server).start(0xc000518000, 0xc000518000, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/tcp/tcp.go:79 +0x13a
github.com/schollz/croc/v8/src/tcp.Run(0x878884, 0x4, 0x0, 0x0, 0x87ccef, 0x7, 0xc00048bfa8, 0x1, 0x1, 0x0, ...)
	/home/zns/go/src/github.com/schollz/croc/src/tcp/tcp.go:50 +0xbe
github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay.func1(0xc000082780, 0x0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:251 +0x12a
created by github.com/schollz/croc/v8/src/croc.(*Client).setupLocalRelay
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:246 +0x85

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x7f5885d5bff8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc000114398, 0x72, 0x0, 0x4, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000114380, 0xc0004580b8, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000114380, 0xc0004580b8, 0x4, 0x4, 0xc00068db78, 0x4490fc, 0x4)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0005d2008, 0xc0004580b8, 0x4, 0x4, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x8e
github.com/schollz/croc/v8/src/comm.(*Comm).Read(0xc0005007a0, 0xc0001f60d0, 0xce, 0xd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/comm/comm.go:77 +0xbb
github.com/schollz/croc/v8/src/comm.(*Comm).Receive(...)
	/home/zns/go/src/github.com/schollz/croc/src/comm/comm.go:120
github.com/schollz/croc/v8/src/croc.(*Client).transfer(0xc000082780, 0xc00017c000, 0x1cb, 0x200, 0x1, 0x3, 0xc000122bc0)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:549 +0xf7
github.com/schollz/croc/v8/src/croc.(*Client).Send.func1(0xc000082780, 0xc000513aa0, 0xc00017c000, 0x1cb, 0x200, 0xc000513a01)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:396 +0xa15
created by github.com/schollz/croc/v8/src/croc.(*Client).Send
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:338 +0x2b9

goroutine 21 [sleep, 5 minutes]:
time.Sleep(0x8bb2c97000)
	/usr/local/go/src/runtime/time.go:198 +0xba
github.com/schollz/croc/v8/src/tcp.(*server).start.func1(0xc000518000)
	/home/zns/go/src/github.com/schollz/croc/src/tcp/tcp.go:63 +0x1ec
created by github.com/schollz/croc/v8/src/tcp.(*server).start
	/home/zns/go/src/github.com/schollz/croc/src/tcp/tcp.go:61 +0x12c

goroutine 36 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f5885d5bd58, 0x72, 0xc0004a61c0)
	/usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0005bc998, 0x72, 0xc000158400, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).RawRead(0xc0005bc980, 0xc0001584e0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:534 +0xf6
net.(*rawConn).Read(0xc00051c3b8, 0xc0001584e0, 0x1, 0x1)
	/usr/local/go/src/net/rawconn.go:43 +0x68
golang.org/x/net/internal/socket.(*Conn).recvMsg(0xc0005ba2a0, 0xc000402d80, 0x0, 0x0, 0x0)
	/home/zns/go/pkg/mod/golang.org/x/net@v0.0.0-20200226121028-0de0cce0169b/internal/socket/rawconn_msg.go:32 +0x20e
golang.org/x/net/internal/socket.(*Conn).RecvMsg(...)
	/home/zns/go/pkg/mod/golang.org/x/net@v0.0.0-20200226121028-0de0cce0169b/internal/socket/socket.go:255
golang.org/x/net/ipv4.(*payloadHandler).ReadFrom(0xc0000660b0, 0xc000294000, 0x103cb, 0x103cb, 0xc000402e38, 0x4490fc, 0x12000, 0x7e8ac0, 0x1, 0xc000294000)
	/home/zns/go/pkg/mod/golang.org/x/net@v0.0.0-20200226121028-0de0cce0169b/ipv4/payload_cmsg.go:31 +0x1a7
github.com/schollz/peerdiscovery.PacketConn4.ReadFrom(0xc0000660a0, 0xc000294000, 0x103cb, 0x103cb, 0xc0000d8868, 0x1, 0x0, 0x0, 0x0)
	/home/zns/go/pkg/mod/github.com/schollz/peerdiscovery@v1.5.0/peerdiscovery.go:376 +0x53
github.com/schollz/peerdiscovery.(*peerDiscovery).listen(0xc0000ce370, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/zns/go/pkg/mod/github.com/schollz/peerdiscovery@v1.5.0/peerdiscovery.go:300 +0x483
created by github.com/schollz/peerdiscovery.Discover
	/home/zns/go/pkg/mod/github.com/schollz/peerdiscovery@v1.5.0/peerdiscovery.go:189 +0x52e

goroutine 1230 [runnable]:
compress/flate.newHuffmanEncoder(...)
	/usr/local/go/src/compress/flate/huffman_code.go:60
compress/flate.newHuffmanBitWriter(...)
	/usr/local/go/src/compress/flate/huffman_bit_writer.go:101
compress/flate.(*compressor).init(0xc000736000, 0x914360, 0xc000418000, 0xfffffffffffffffe, 0xc000081c00, 0x7f58ac9e47d0)
	/usr/local/go/src/compress/flate/deflate.go:579 +0x1c5
compress/flate.NewWriter(0x914360, 0xc000418000, 0xfffffffffffffffe, 0x40c7d8, 0x30, 0x8330c0)
	/usr/local/go/src/compress/flate/deflate.go:671 +0x62
github.com/schollz/croc/v8/src/compress.compress(0xc000252000, 0x8008, 0xa000, 0x914360, 0xc000418000, 0xfffffffffffffffe)
	/home/zns/go/src/github.com/schollz/croc/src/compress/compress.go:33 +0x3f
github.com/schollz/croc/v8/src/compress.Compress(...)
	/home/zns/go/src/github.com/schollz/croc/src/compress/compress.go:19
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc000082780, 0x1)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1213 +0x396
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1079 +0x34e

goroutine 1232 [semacquire]:
sync.runtime_SemacquireMutex(0xc0000b68c4, 0x0, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000b68c0)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc000082780, 0x3)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1198 +0x616
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1079 +0x34e

goroutine 1229 [runnable]:
compress/flate.(*compressor).close(0xc000694000, 0xc00022c000, 0x8008)
	/usr/local/go/src/compress/flate/deflate.go:641 +0x114
compress/flate.(*Writer).Close(...)
	/usr/local/go/src/compress/flate/deflate.go:732
github.com/schollz/croc/v8/src/compress.compress(0xc00022c000, 0x8008, 0xa000, 0x914360, 0xc0000982d0, 0xfffffffffffffffe)
	/home/zns/go/src/github.com/schollz/croc/src/compress/compress.go:35 +0x81
github.com/schollz/croc/v8/src/compress.Compress(...)
	/home/zns/go/src/github.com/schollz/croc/src/compress/compress.go:19
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc000082780, 0x0)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1213 +0x396
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1079 +0x34e
```

**Comment by schollz** [comment]
Thanks. The source of this bug is not obvious to me, but I pushed a change that might fix it. Are you seeing this repeatedly?
