### ISSUE TITLE
Initial Read Error when Transferring from Windows to Linux

### ISSUE THREAD

**Issue by lazerl0rd** [schollz/croc#425]
## Describe the bug
I'm unable to transfer files from the Windows server (Windows 11, Build 22000.194) to a Linux client (Arch Linux, Updated as of 03/10/2021) over LAN. Firewall exemptions have been set on both sides.

## To Reproduce
1. Install croc on both sides.
2. Run `croc --local send <filename>` on the Windows "server".
3. Run `croc --ip <server-ip> <code>` on the Linux "client" with the code given by the server.
4. Cry when it doesn't work.

## Expected behaviour
The file transfer to complete, or at least start.

## Version
The server and client are both running `croc version v9.4.2-49f50a5`. 

## Additional context
The server log is as follows:
```
$ croc --debug --local --no-compress send .\vroom.zip
[debug] 22:00:18 cli.go:163: debug mode on
[debug] 22:00:18 croc.go:169: options: {IsSender:true SharedSecret:<REDACTED> Debug:true RelayAddress:<REDACTED>:9009 RelayAddress6:[<REDACTED>]:9009 RelayPorts:[9009 9010 9011 9012 9013] RelayPassword:<REDACTED> Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:true IgnoreStdin:false Ask:false SendingText:false NoCompress:true IP: Overwrite:false Curve:siec HashAlgorithm:xxhash}
[debug] 22:01:00 croc.go:236: hashed C:\Fakepath\vroom.zip to b2390a8a8a011456 using xxhash
[debug] 22:01:00 croc.go:262: file 0 info: {Name:vroom.zip FolderRemote:. FolderSource:C:\Fakepath\ Hash:[178 57 10 138 138 1 20 86] Size:23686687548 ModTime:2021-10-03 19:23:02.5382622 +0100 BST IsCompressed:false IsEncrypted:false Symlink:}
Sending 0 files (22.1 GB)[debug]        22:01:00 croc.go:266: longestFilename: 9
Sending 'vroom.zip' (22.1 GB)
Code is: <REDACTED>
On the other computer run

croc <REDACTED>
[debug] 22:01:00 tcp.go:60: starting with password '<REDACTED>'
[debug] 22:01:00 tcp.go:60: starting with password '<REDACTED>'
[debug] 22:01:00 tcp.go:60: starting with password '<REDACTED>'
[debug] 22:01:00 tcp.go:60: starting with password '<REDACTED>'
[debug] 22:01:00 tcp.go:60: starting with password '<REDACTED>'
[info]  2021/10/03 22:01:00 starting TCP server on 0.0.0.0:9009
[info]  2021/10/03 22:01:00 starting TCP server on 0.0.0.0:9012
[info]  2021/10/03 22:01:00 starting TCP server on 0.0.0.0:9010
[info]  2021/10/03 22:01:00 starting TCP server on 0.0.0.0:9013
[info]  2021/10/03 22:01:00 starting TCP server on 0.0.0.0:9011
[debug] 22:01:01 croc.go:329: establishing connection
[debug] 22:01:01 comm.go:55: dialing to localhost:9009 with timelimit 30s
[debug] 22:01:01 comm.go:64: connected to 'localhost:9009'
[debug] 22:01:01 tcp.go:125: client 127.0.0.1:57117 connected
[debug] 22:01:01 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:01:01 tcp.go:207: strongkey: <REDACTED>
[debug] 22:01:01 tcp.go:476: strong key: <REDACTED>
[debug] 22:01:01 tcp.go:490: sending password
[debug] 22:01:01 tcp.go:219: waiting for password
[debug] 22:01:01 tcp.go:501: waiting for first ok
[debug] 22:01:01 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:01:01 tcp.go:253: waiting for answer
[debug] 22:01:01 tcp.go:519: sending room
[debug] 22:01:01 tcp.go:530: waiting for room confirmation
[debug] 22:01:01 tcp.go:546: all set
[debug] 22:01:01 tcp.go:284: room 178 has 1
[debug] 22:01:01 croc.go:332: banner: 9010,9011,9012,9013
[debug] 22:01:01 tcp.go:129: room: 178
[debug] 22:01:01 tcp.go:130: err: <nil>
[debug] 22:01:01 tcp.go:143: checking connection of room 178 for &{connection:0xc0002ac008}
[debug] 22:01:01 croc.go:339: local connection established: &{connection:0xc000216000}
[debug] 22:01:01 tcp.go:151: room: {first:0xc00018c090 second:<nil> opened:{wall:13857193850461797772 ext:43510326701 loc:0x952400} full:false}
[debug] 22:01:01 croc.go:345: got ping
...
[debug] 22:14:18 tcp.go:143: checking connection of room 178 for &{connection:0xc0002ac008}
[debug] 22:14:18 tcp.go:151: room: {first:0xc00018c090 second:<nil> opened:{wall:13857193850461797772 ext:43510326701 loc:0x952400} full:false}
[debug] 22:14:18 croc.go:345: got ping
[debug] 22:14:18 tcp.go:125: client <REDACTED>:44798 connected
[debug] 22:14:18 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:18 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:18 tcp.go:219: waiting for password
[debug] 22:14:18 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:18 tcp.go:253: waiting for answer
[debug] 22:14:18 tcp.go:300: room 178 has 2
[debug] 22:14:18 tcp.go:316: starting pipes
[debug] 22:14:18 croc.go:351: exchanged header message
[debug] 22:14:18 croc.go:712: ready
[debug] 22:14:18 message.go:80: read pake message (unencrypted)
[debug] 22:14:18 croc.go:853: received pake payload
[debug] 22:14:18 croc.go:858: using curve siec
[debug] 22:14:18 croc.go:872: generating salt
[debug] 22:14:18 croc.go:878: sender sending pake+salt
[debug] 22:14:18 message.go:61: writing pake message (unencrypted)
[debug] 22:14:18 croc.go:900: generated key = <REDACTED> with salt <REDACTED>
[debug] 22:14:18 croc.go:906: port: [9010]
[debug] 22:14:18 croc.go:906: port: [9011]
[debug] 22:14:18 croc.go:906: port: [9012]
[debug] 22:14:18 croc.go:906: port: [9013]
[debug] 22:14:18 croc.go:920: connecting to localhost:9013
[debug] 22:14:18 comm.go:55: dialing to localhost:9013 with timelimit 30s
[debug] 22:14:18 croc.go:920: connecting to localhost:9010
[debug] 22:14:18 croc.go:920: connecting to localhost:9011
[debug] 22:14:18 comm.go:55: dialing to localhost:9011 with timelimit 30s
[debug] 22:14:18 croc.go:920: connecting to localhost:9012
[debug] 22:14:18 comm.go:55: dialing to localhost:9012 with timelimit 30s
[debug] 22:14:18 comm.go:55: dialing to localhost:9010 with timelimit 30s
[debug] 22:14:18 tcp.go:125: client <REDACTED>:52658 connected
[debug] 22:14:18 tcp.go:125: client <REDACTED>:48178 connected
[debug] 22:14:18 tcp.go:125: client <REDACTED>:32392 connected
[debug] 22:14:18 tcp.go:125: client <REDACTED>:64374 connected
[debug] 22:14:18 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:18 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:18 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:18 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:18 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:18 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:18 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:18 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:18 tcp.go:219: waiting for password
[debug] 22:14:18 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:18 tcp.go:253: waiting for answer
[debug] 22:14:18 tcp.go:219: waiting for password
[debug] 22:14:18 tcp.go:219: waiting for password
[debug] 22:14:18 tcp.go:219: waiting for password
[debug] 22:14:18 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:18 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:18 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:18 tcp.go:253: waiting for answer
[debug] 22:14:18 tcp.go:253: waiting for answer
[debug] 22:14:18 tcp.go:253: waiting for answer
[debug] 22:14:18 tcp.go:284: room 908de2-1 has 1
[debug] 22:14:18 tcp.go:129: room: 908de2-1
[debug] 22:14:18 tcp.go:130: err: <nil>
[debug] 22:14:18 tcp.go:284: room 908de2-0 has 1
[debug] 22:14:18 tcp.go:129: room: 908de2-0
[debug] 22:14:18 tcp.go:143: checking connection of room 908de2-1 for &{connection:0xc0000de030}
[debug] 22:14:18 tcp.go:151: room: {first:0xc0000984e0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:18 tcp.go:284: room 908de2-3 has 1
[debug] 22:14:18 tcp.go:129: room: 908de2-3
[debug] 22:14:18 tcp.go:130: err: <nil>
[debug] 22:14:18 tcp.go:143: checking connection of room 908de2-3 for &{connection:0xc0001ae000}
[debug] 22:14:18 tcp.go:151: room: {first:0xc00020c100 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:18 tcp.go:130: err: <nil>
[debug] 22:14:18 tcp.go:284: room 908de2-2 has 1
[debug] 22:14:18 tcp.go:129: room: 908de2-2
[debug] 22:14:18 tcp.go:130: err: <nil>
[debug] 22:14:18 tcp.go:143: checking connection of room 908de2-2 for &{connection:0xc0000de018}
[debug] 22:14:18 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:18 tcp.go:151: room: {first:0xc00020c0c0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:18 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:19 comm.go:64: connected to 'localhost:9010'
[debug] 22:14:19 tcp.go:125: client 127.0.0.1:58027 connected
[debug] 22:14:19 tcp.go:125: client 127.0.0.1:58026 connected
[debug] 22:14:19 comm.go:64: connected to 'localhost:9011'
[debug] 22:14:19 tcp.go:125: client 127.0.0.1:58029 connected
[debug] 22:14:19 comm.go:64: connected to 'localhost:9012'
[debug] 22:14:19 comm.go:64: connected to 'localhost:9013'
[debug] 22:14:19 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:19 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:19 tcp.go:188: Abytes: {"Role":0,"Uᵤ":<REDACTED>,"Uᵥ":<REDACTED>,"Vᵤ":<REDACTED>,"Vᵥ":<REDACTED>,"Xᵤ":<REDACTED>,"Xᵥ":<REDACTED>,"Yᵤ":null,"Yᵥ":null,"Pw":null,"Vpwᵤ":null,"Vpwᵥ":null,"Upwᵤ":null,"Upwᵥ":null,"Aα":null,"Aαᵤ":null,"Aαᵥ":null,"Zᵤ":null,"Zᵥ":null,"K":null}
[debug] 22:14:19 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:19 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:19 tcp.go:207: strongkey: <REDACTED>
[debug] 22:14:19 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:19 tcp.go:490: sending password
[debug] 22:14:19 tcp.go:219: waiting for password
[debug] 22:14:19 tcp.go:501: waiting for first ok
[debug] 22:14:19 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:19 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:19 tcp.go:490: sending password
[debug] 22:14:19 tcp.go:219: waiting for password
[debug] 22:14:19 tcp.go:501: waiting for first ok
[debug] 22:14:19 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:19 tcp.go:519: sending room
[debug] 22:14:19 tcp.go:253: waiting for answer
[debug] 22:14:19 tcp.go:530: waiting for room confirmation
[debug] 22:14:19 tcp.go:300: room 908de2-1 has 2
[debug] 22:14:19 tcp.go:253: waiting for answer
[debug] 22:14:19 tcp.go:546: all set
[debug] 22:14:19 tcp.go:519: sending room
[debug] 22:14:19 tcp.go:316: starting pipes
[debug] 22:14:19 tcp.go:300: room 908de2-2 has 2
[debug] 22:14:19 croc.go:929: connected to localhost:9011
[debug] 22:14:19 tcp.go:530: waiting for room confirmation
[debug] 22:14:19 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:19 tcp.go:316: starting pipes
[debug] 22:14:19 tcp.go:546: all set
[debug] 22:14:19 croc.go:929: connected to localhost:9012
[debug] 22:14:19 tcp.go:490: sending password
[debug] 22:14:19 tcp.go:219: waiting for password
[debug] 22:14:19 tcp.go:501: waiting for first ok
[debug] 22:14:19 tcp.go:242: sending '9010,9011,9012,9013'
[debug] 22:14:19 tcp.go:253: waiting for answer
[debug] 22:14:19 tcp.go:519: sending room
[debug] 22:14:19 tcp.go:530: waiting for room confirmation
[debug] 22:14:19 tcp.go:300: room 908de2-3 has 2
[debug] 22:14:19 tcp.go:316: starting pipes
[debug] 22:14:19 tcp.go:546: all set
[debug] 22:14:19 croc.go:929: connected to localhost:9013
[debug] 22:14:19 tcp.go:143: checking connection of room 178 for &{connection:0xc0002ac008}
[debug] 22:14:19 tcp.go:151: room: {first:0xc00018c090 second:0xc0000985b0 opened:{wall:13857193850461797772 ext:43510326701 loc:0x952400} full:true}
[debug] 22:14:19 tcp.go:153: rooms ready
[debug] 22:14:19 tcp.go:143: checking connection of room 908de2-2 for &{connection:0xc0000de018}
[debug] 22:14:19 tcp.go:151: room: {first:0xc00020c0c0 second:0xc0004c80c0 opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:true}
[debug] 22:14:19 tcp.go:153: rooms ready
[debug] 22:14:19 tcp.go:143: checking connection of room 908de2-1 for &{connection:0xc0000de030}
[debug] 22:14:19 tcp.go:151: room: {first:0xc0000984e0 second:0xc00018c0e0 opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:true}
[debug] 22:14:19 tcp.go:153: rooms ready
[debug] 22:14:19 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:19 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:19 tcp.go:143: checking connection of room 908de2-3 for &{connection:0xc0001ae000}
[debug] 22:14:19 tcp.go:151: room: {first:0xc00020c100 second:0xc00044a010 opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:true}
[debug] 22:14:19 tcp.go:153: rooms ready
[debug] 22:14:20 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:20 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:21 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:21 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:22 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:22 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:23 tcp.go:143: checking connection of room 908de2-0 for &{connection:0xc0000de028}
[debug] 22:14:23 tcp.go:151: room: {first:0xc00020c0d0 second:<nil> opened:{wall:13857194706202818500 ext:840479113701 loc:0x952400} full:false}
[debug] 22:14:24 comm.go:128: initial read error: EOF
[debug] 22:14:24 tcp.go:463: EOF
panic: EOF

goroutine 118 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake.func1(0x0)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:927 +0x4f5
created by github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:907 +0x7b2
```

The client log is as follows:
```
$ croc --debug --ip <REDACTED> --no-compress <REDACTED>
[debug] 22:14:18 cli.go:163: debug mode on
[debug] 22:14:18 croc.go:169: options: {IsSender:false SharedSecret:<REDACTED> Debug:true RelayAddress:<REDACTED>:9009 RelayAddress6:[<REDACTED>]:9009 RelayPorts:[] RelayPassword:<REDACTED> Stdout:false NoPrompt:false NoMultiplexing:false DisableLocal:false OnlyLocal:false IgnoreStdin:false Ask:false SendingText:false NoCompress:false IP:<REDACTED> Overwrite:false Curve:siec HashAlgorithm:}
connecting...[debug]    22:14:18 croc.go:521: assume ipv4
[debug] 22:14:18 croc.go:610: got host '<REDACTED>' and port '9009'
[debug] 22:14:18 croc.go:612: trying connection to <REDACTED>:9009
[debug] 22:14:18 comm.go:55: dialing to <REDACTED>:9009 with timelimit 5s
[debug] 22:14:18 comm.go:64: connected to '<REDACTED>:9009'
[debug] 22:14:18 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:18 tcp.go:490: sending password
[debug] 22:14:18 tcp.go:501: waiting for first ok
[debug] 22:14:18 tcp.go:519: sending room
[debug] 22:14:18 tcp.go:530: waiting for room confirmation
[debug] 22:14:18 tcp.go:546: all set
[debug] 22:14:18 croc.go:625: receiver connection established: &{connection:0xc000094000}
[debug] 22:14:18 croc.go:626: banner: 9010,9011,9012,9013
[debug] 22:14:18 croc.go:694: exchanged header message
securing channel...[debug]      22:14:18 croc.go:712: ready
[debug] 22:14:18 message.go:61: writing pake message (unencrypted)
[debug] 22:14:18 message.go:80: read pake message (unencrypted)
[debug] 22:14:18 croc.go:853: received pake payload
[debug] 22:14:18 croc.go:900: generated key = <REDACTED> with salt <REDACTED>
[debug] 22:14:18 croc.go:906: port: [9010]
[debug] 22:14:18 croc.go:906: port: [9011]
[debug] 22:14:18 croc.go:906: port: [9012]
[debug] 22:14:18 croc.go:906: port: [9013]
[debug] 22:14:18 croc.go:920: connecting to <REDACTED>:9013
[debug] 22:14:18 croc.go:920: connecting to <REDACTED>:9011
[debug] 22:14:18 croc.go:920: connecting to <REDACTED>:9012
[debug] 22:14:18 comm.go:55: dialing to <REDACTED>:9012 with timelimit 30s
[debug] 22:14:18 croc.go:920: connecting to <REDACTED>:9010
[debug] 22:14:18 comm.go:55: dialing to <REDACTED>:9010 with timelimit 30s
[debug] 22:14:18 comm.go:55: dialing to <REDACTED>:9011 with timelimit 30s
[debug] 22:14:18 comm.go:55: dialing to <REDACTED>:9013 with timelimit 30s
[debug] 22:14:18 comm.go:64: connected to '<REDACTED>:9011'
[debug] 22:14:18 comm.go:64: connected to '<REDACTED>:9010'
[debug] 22:14:18 comm.go:64: connected to '<REDACTED>:9012'
[debug] 22:14:18 comm.go:64: connected to '<REDACTED>:9013'
[debug] 22:14:18 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:18 tcp.go:490: sending password
[debug] 22:14:18 tcp.go:501: waiting for first ok
[debug] 22:14:18 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:18 tcp.go:490: sending password
[debug] 22:14:18 tcp.go:501: waiting for first ok
[debug] 22:14:18 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:18 tcp.go:490: sending password
[debug] 22:14:18 tcp.go:501: waiting for first ok
[debug] 22:14:18 tcp.go:476: strong key: <REDACTED>
[debug] 22:14:18 tcp.go:490: sending password
[debug] 22:14:18 tcp.go:501: waiting for first ok
[debug] 22:14:18 tcp.go:519: sending room
[debug] 22:14:18 tcp.go:519: sending room
[debug] 22:14:18 tcp.go:519: sending room
[debug] 22:14:18 tcp.go:530: waiting for room confirmation
[debug] 22:14:18 tcp.go:530: waiting for room confirmation
[debug] 22:14:18 tcp.go:519: sending room
[debug] 22:14:18 tcp.go:530: waiting for room confirmation
[debug] 22:14:18 tcp.go:530: waiting for room confirmation
[debug] 22:14:18 tcp.go:546: all set
[debug] 22:14:18 tcp.go:546: all set
[debug] 22:14:18 croc.go:929: connected to <REDACTED>:9012
[debug] 22:14:18 croc.go:929: connected to <REDACTED>:9010
[debug] 22:14:18 croc.go:1436: 2 receiving data
[debug] 22:14:18 tcp.go:546: all set
[debug] 22:14:18 croc.go:929: connected to <REDACTED>:9011
[debug] 22:14:18 croc.go:1436: 1 receiving data
[debug] 22:14:18 croc.go:1436: 0 receiving data
[debug] 22:14:18 tcp.go:546: all set
[debug] 22:14:18 croc.go:929: connected to <REDACTED>:9013
[debug] 22:14:18 croc.go:938: sending external IP
[debug] 22:14:18 croc.go:1436: 3 receiving data
[debug] 22:14:18 croc.go:1443: got ping
[debug] 22:14:18 message.go:58: writing externalip message (encrypted)
[debug] 22:14:18 croc.go:1443: got ping
[debug] 22:14:18 croc.go:1443: got ping
[debug] 22:14:18 croc.go:1443: got ping
[debug] 22:14:19 croc.go:1443: got ping
[debug] 22:14:20 croc.go:1443: got ping
[debug] 22:14:21 croc.go:1443: got ping
[debug] 22:14:22 croc.go:1443: got ping
[debug] 22:14:24 croc.go:1443: got ping
[debug] 22:14:24 comm.go:128: initial read error: read tcp <REDACTED>:44798-><REDACTED>:9009: read: connection reset by peer
[debug] 22:14:24 comm.go:128: initial read error: read tcp <REDACTED>:48178-><REDACTED>:9010: read: connection reset by peer
[debug] 22:14:24 comm.go:128: initial read error: read tcp <REDACTED>:52658-><REDACTED>:9012: read: connection reset by peer
[debug] 22:14:24 comm.go:128: initial read error: read tcp <REDACTED>:64374-><REDACTED>:9013: read: connection reset by peer
[debug] 22:14:24 croc.go:730: got error receiving: read tcp <REDACTED>:44798-><REDACTED>:9009: read: connection reset by peer
[debug] 22:14:24 comm.go:128: initial read error: read tcp <REDACTED>:32392-><REDACTED>:9011: read: connection reset by peer
2021/10/03 22:14:24 could not secure channel
```

**Comment by schollz** [comment]
does it work without using `--ip`?

**Comment by lazerl0rd** [comment]
> does it work without using `--ip`?

Nope. Here's the "short" log:

```log
Sending '.wslconfig' (500 B)
Code is: <REDACTED>
On the other computer run

croc <REDACTED>
panic: EOF

goroutine 26 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake.func1(0x0)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:927 +0x4f5
created by github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:907 +0x7b2
```
