### ISSUE TITLE
Empty folder exception gives error

### ISSUE THREAD

**Issue by pablodz** [schollz/croc#463]
## Describe the bug

When sending a empty folder, it occurs an not handled exception

## To Reproduce

1. create folder
2. send with `croc *`
3. error occurs

## Expected behaviour

Create the empty folder in receiver

## Version

croc version v9.5.1-b0e7d4d

## Additional context

```
Receiving (<-100.25.195.96:51768)
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).recipientInitializeFile(0xc000202000)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1131 +0x6bb
github.com/schollz/croc/v9/src/croc.(*Client).recipientGetFileReady(0xc000202000, 0x1)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1194 +0x145
github.com/schollz/croc/v9/src/croc.(*Client).updateIfRecipientHasFileInfo(0xc0000ca000)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1355 +0x8b
github.com/schollz/croc/v9/src/croc.(*Client).updateState(0xc000202000)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1374 +0x4c
github.com/schollz/croc/v9/src/croc.(*Client).processMessage(0xc000202000, {0xc00012c0e0, 0x0, 0x0})
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1088 +0x929
github.com/schollz/croc/v9/src/croc.(*Client).transfer(0xc000202000, {{0xc00000e020, 0x6f5ba2, 0x14}, 0x0})
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:769 +0x270
github.com/schollz/croc/v9/src/croc.(*Client).Receive(0xc000202000)
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:729 +0x16d5
github.com/schollz/croc/v9/src/cli.receive(0xc0000ad040)
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:499 +0xd72
github.com/schollz/croc/v9/src/cli.Run.func1(0xc0000ad040)
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:132 +0x172
github.com/schollz/cli/v2.(*App).RunContext(0xc00015e600, {0x756010, 0xc000014100}, {0xc000010040, 0x2, 0x2})
	/home/zns/go/pkg/mod/github.com/schollz/cli/v2@v2.2.1/app.go:315 +0x7a8
github.com/schollz/cli/v2.(*App).Run(...)
	/home/zns/go/pkg/mod/github.com/schollz/cli/v2@v2.2.1/app.go:217
github.com/schollz/croc/v9/src/cli.Run()
	/home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:135 +0x12e5
main.main()
	/home/zns/go/src/github.com/schollz/croc/main.go:30 +0x19

```

**Comment by schollz** [comment]
Thanks @pablodz, would accept a PR fixing this
