### ISSUE TITLE
does not work on windows server 2018

### ISSUE THREAD

**Issue by ciis0** [schollz/croc#471]
## Describe the bug

croc crashes on Windows Server 2018.

```
PS > .\croc.exe -v
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive, locked to thread]:
github.com/schollz/croc/v9/src/models.lookup({0x14d1519, 0x11})
        /home/zns/go/src/github.com/schollz/croc/src/models/constants.go:111 +0xec
github.com/schollz/croc/v9/src/models.init.0()
        /home/zns/go/src/github.com/schollz/croc/src/models/constants.go:88 +0x158
```

![image](https://user-images.githubusercontent.com/16290850/165540916-b0866697-8547-4eee-bf1b-f4798a114d6e.png)

## To Reproduce

1. simply run croc.

## Version

croc -v crashes, but the ZIP is croc_9.5.3_Windows-64bit.

**Comment by ciis0** [comment]
Unfortunately not easily, no, I do not have a go environment setup currently. But I'll try.

**Comment by ciis0** [comment]
huh, that was easy!

does seem to work. :)

```
PS > .\croc -v
croc version v9.5.3-54f52e5
```

**Comment by ciis0** [comment]
confusing that it shows `-54f52e5` though. ^^

**Comment by schollz** [comment]
cool. fixed in v9.5.4
