### ISSUE TITLE
Allow performing multiple sends at the same time from a single machine

### ISSUE THREAD

**Issue by TheFiZi** [schollz/croc#510]
**Is your feature request related to a problem? Please describe.**
When I attempt to send two different files to two different machines at the same time croc will only successfully start one transfer at a time. I suspect this is because it expects a fixed set of local ports to be available and does not increment the port number if the expected port is unavailable. This happens on public and private relays.

This also fixes a second edge case where if the port croc is expecting to use for the send is being used by a different app croc would still function.

Unless I am completely miss-understanding what is going on here :)

```
PS D:\> croc --pass MYPASS --relay "MYRELAY:9009" '.\MYFILE\'
Did you mean to send ''? (Y/n) y
Sending 4 files and 1 folders (9.3 GB)
Code is: 1824-ralph-palma-aloha
On the other computer run

croc --relay MYRELAY:9009 --pass MYPASS 1824-ralph-palma-aloha
[error] 2022/10/21 14:46:58 tcp.go:85: error listening on 0.0.0.0:9012: listen tcp4 0.0.0.0:9012: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
[error] 2022/10/21 14:46:58 tcp.go:85: error listening on 0.0.0.0:9010: listen tcp4 0.0.0.0:9010: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.
panic: error listening on 0.0.0.0:9012: listen tcp4 0.0.0.0:9012: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 52 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay.func1({0xc0000ab930, 0x4})
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:444 +0x125
created by github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:437 +0x217
panic: error listening on 0.0.0.0:9010: listen tcp4 0.0.0.0:9010: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 50 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay.func1({0xc0000ab910, 0x4})
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:444 +0x125
created by github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:437 +0x217
        ```

**Describe the solution you'd like**
If croc finds the port it wants to use as in use, increment the port number until it finds a free one.

**Describe alternatives you've considered**
Only start one croc send at a time on any given machine.

**Additional context**
Windows 11, croc 9.6.1

**Comment by TheFiZi** [comment]
This request likely is related to https://github.com/schollz/croc/issues/472
