### ISSUE TITLE
Croc failing on sending file: lookup localhost on 1.1.1.1:53: no such host

### ISSUE THREAD

**Issue by robiot** [schollz/croc#513]
## Describe the bug
Croc failing when trying to setup a local relay.
```
Did you mean to send 'file.zip'? (Y/n)
Sending 'file.zip' (20 kB)
Code is: x
On the other computer run

croc x
[error]	[date] tcp.go:85: lookup localhost on 1.1.1.1:53: no such host
panic: lookup localhost on 1.1.1.1:53: no such host

goroutine 36 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay.func1({0x9168c0, 0x1})
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:334 +0x125
created by github.com/schollz/croc/v9/src/croc.(*Client).setupLocalRelay
	/home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:327 +0x211
```

## To Reproduce
I actually do not know why this started to happen. But I suppose it has something with 1.1.1.1 to do. And I got no clue why it is trying to request port 53 on cloudflares DNS server.

## Expected behaviour
Should work normally.

## Version
croc version v9.5.1-b0e7d4d

**Comment by schollz** [comment]
Do you get this error on the latest version?

**Comment by robiot** [comment]
croc version v9.6.1-b27982a
Yep happens on the latest too.

Supposedly it is a problem on my end, but I still haven't figured out what 😅

**Comment by schollz** [comment]
thanks @xeizmendi , I will change all the "localhost" to 127.0.0.1
