### ISSUE TITLE
Errors about customizing Relay Server

### ISSUE THREAD

**Issue by Kry1702** [schollz/croc#541]
## Describe the bug
<-- A clear and concise description of what the bug is. -->
Error when receiving file.

## To Reproduce
1. croc relay --ports 3001
2.croc --relay 192.168.39.83:3001 send env.file
3. Receiver executes “croc --relay 192.168.39.83:3001 4572-prism-sleep-escape” ，The error message is as follows
```
securing channel...panic: comm.NewConnection failed: dial tcp: lookup tcp/ok: getaddrinfow: The specified class was not found.

goroutine 22 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake.func1(0x0)
        /home/zns/Documents/croc/src/croc/croc.go:1180 +0x4f8
created by github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake
        /home/zns/Documents/croc/src/croc/croc.go:1160 +0x7ec
```

sender error
```
panic: comm.NewConnection failed: dial tcp: address tcp/ok: unknown port

goroutine 64 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake.func1(0x0)
	/home/zns/Documents/croc/src/croc/croc.go:1174 +0x4f5
created by github.com/schollz/croc/v9/src/croc.(*Client).processMessagePake
	/home/zns/Documents/croc/src/croc/croc.go:1154 +0x7ec

``


## Version
<-- Check "croc -v" and report it -->
croc version v9.6.2-3b8193

**Comment by schollz** [comment]
I cannot reproduce this error. 

Are you sure your relay address is available from the sender?
