### ISSUE TITLE
Receiving an empty folder throws Exception

### ISSUE THREAD

**Issue by black-fake** [schollz/croc#604]
## Describe the bug

When sending only an empty folder, an ```index out of range``` error occurs on the receiver side

## To Reproduce
1. Create new directory on sender site ```mkdir <new_dir>```
2. send only this empty directory with ```croc send <new_dir>```
3. Receive and accept it on receiver side ```croc <provided_sending_key>```
4. See error, because nothing was received

## Expected behaviour
Creation of empty folder ```<new_dir>``` on receiver side

## Version
croc version v9.5.1-b0e7d4d

### Sender
```
$ croc send html/
Sending 0 files and 1 folders (0 B)
Code is: 2373-sport-sister-chef
On the other computer run

croc 2373-sport-sister-chef
```

### Receiver
```
$ croc 2373-sport-sister-chef
Accept 0 files (0 B)? (Y/n) 

Receiving (<-<some-ip>:41958)
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/schollz/croc/v9/src/croc.(*Client).recipientInitializeFile(0xc000158000)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1131 +0x6bb
github.com/schollz/croc/v9/src/croc.(*Client).recipientGetFileReady(0xc000158000, 0x1)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1194 +0x145
github.com/schollz/croc/v9/src/croc.(*Client).updateIfRecipientHasFileInfo(0xc000110090)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1355 +0x8b
github.com/schollz/croc/v9/src/croc.(*Client).updateState(0xc000158000)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1374 +0x4c
github.com/schollz/croc/v9/src/croc.(*Client).processMessage(0xc000158000, {0xc0000e0140, 0x0, 0x0})
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:1088 +0x929
github.com/schollz/croc/v9/src/croc.(*Client).transfer(0xc000158000, {{0xc00000e028, 0x6f5ba2, 0x14}, 0x0})
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:769 +0x270
github.com/schollz/croc/v9/src/croc.(*Client).Receive(0xc000158000)
        /home/zns/go/src/github.com/schollz/croc/src/croc/croc.go:729 +0x16d5
github.com/schollz/croc/v9/src/cli.receive(0xc0000750c0)
        /home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:499 +0xd72
github.com/schollz/croc/v9/src/cli.Run.func1(0xc0000750c0)
        /home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:132 +0x172
github.com/schollz/cli/v2.(*App).RunContext(0xc000122600, {0x756010, 0xc0000140b0}, {0xc000010040, 0x2, 0x2})
        /home/zns/go/pkg/mod/github.com/schollz/cli/v2@v2.2.1/app.go:315 +0x7a8
github.com/schollz/cli/v2.(*App).Run(...)
        /home/zns/go/pkg/mod/github.com/schollz/cli/v2@v2.2.1/app.go:217
github.com/schollz/croc/v9/src/cli.Run()
        /home/zns/go/src/github.com/schollz/croc/src/cli/cli.go:135 +0x12e5
main.main()
        /home/zns/go/src/github.com/schollz/croc/main.go:30 +0x19
```

### similar issue
#463

**Comment by schollz** [comment]
Can you replicate this on the latest version (9.6.5)? I can't replicate it.

**Comment by black-fake** [comment]
Ah, you're correct - it does work like a charm with the newest version :)
I somehow assumed that I already was on the newest one. Sorry for bothering

P.S. I'm so glad you made this piece of software, actually I use it almost every day and it makes my life so much easier 👍 
Thanks

**Comment by stefins** [comment]
This can be closed
