### ISSUE TITLE
write: broken pipe panic when receiver runs out of disk space

### ISSUE THREAD

**Issue by twpayne** [schollz/croc#791]
Firstly, thank you for this excellent software! It's fantastically helpful!

I was testing croc to send a file over my LAN and sender panicked when the receiver ran out of disk space:

```
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9012->192.168.50.101:34770: write: broken pipe
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9011->192.168.50.101:52906: write: broken pipe
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9011->192.168.50.101:52906: write: broken pipe
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9011->192.168.50.101:52906: write: broken pipe
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9010->192.168.50.101:40064: write: broken pipe
[error] 2024/08/29 22:05:48 tcp.go:445: write error on channel 2: write tcp4 192.168.50.237:9010->192.168.50.101:40064: write: broken pipe
panic: connection.Write failed: write tcp 127.0.0.1:51475->127.0.0.1:9012: write: broken pipe

goroutine 133 [running]:
github.com/schollz/croc/v10/src/croc.(*Client).sendData(0x1400022c008, 0x2)
        github.com/schollz/croc/v10/src/croc/croc.go:2063 +0x800
created by github.com/schollz/croc/v10/src/croc.(*Client).updateState in goroutine 31
        github.com/schollz/croc/v10/src/croc/croc.go:1889 +0x500
```

The sender is running:

```console
$ croc --version
croc version v10.0.11
$ uname -a
Darwin Toms-Laptop.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8122 arm64
```

The receiver was:

```console
$ croc --version
croc version v10.0.11
uname -a
Linux ubuntu 6.8.0-41-generic #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Let me know if you'd like more information.

**Comment by twpayne** [comment]
I just noticed that the receiver panicked too:

```console
$ croc
Enter receive code: ***
Accept 'file.iso' (2.3 GB)? (Y/n) Y

Receiving (<-127.0.0.1:51470)
 file.iso...  67% |█████████████       | (1.7/2.5 GB, 118 MB/s) [14s:6s]panic: write file.iso: no space left on device

goroutine 37 [running]:
github.com/schollz/croc/v10/src/croc.(*Client).receiveData(0xc0002c6000, 0x1)
        /home/runner/work/croc/croc/src/croc/croc.go:1964 +0x79e
created by github.com/schollz/croc/v10/src/croc.(*Client).processMessagePake.func1 in goroutine 71
        /home/runner/work/croc/croc/src/croc/croc.go:1417 +0x425
```
