### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by sgon00** [schollz/croc#84]
croc version 3.0.6
Send a folder from WIndows 10 to Arch Linux

```
Sending 5.1 GB folder named 'doc-videos'
Code is: silence-voice-bombay
On the other computer, please run:

croc silence-voice-bombay
- waiting for ok... runtime: VirtualAlloc of 2568749056 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x8a445a, 0xd)
        /usr/local/go/src/runtime/panic.go:616 +0x88
runtime.sysMap(0xc042800000, 0x991c0000, 0x1, 0xb2a6f8)
        /usr/local/go/src/runtime/mem_windows.go:122 +0x13b
runtime.(*mheap).sysAlloc(0xb10f60, 0x991c0000, 0xd53df12d01d419e6)
        /usr/local/go/src/runtime/malloc.go:470 +0xdb
runtime.(*mheap).grow(0xb10f60, 0x4c8dc, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x67
runtime.(*mheap).allocSpanLocked(0xb10f60, 0x4c8dc, 0xb2a708, 0x55005c0000005c)
        /usr/local/go/src/runtime/mheap.go:820 +0x308
runtime.(*mheap).alloc_m(0xb10f60, 0x4c8dc, 0xc0424d0101, 0xc0424d1c80)
        /usr/local/go/src/runtime/mheap.go:686 +0x126
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:753 +0x54
runtime.(*mheap).alloc(0xb10f60, 0x4c8dc, 0x4010101, 0x4140ba)
        /usr/local/go/src/runtime/mheap.go:752 +0x91
runtime.largeAlloc(0x991b6fc5, 0x440101, 0x1906a8)
        /usr/local/go/src/runtime/malloc.go:826 +0x9b
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:721 +0x4d
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:409 +0x7e
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1175

goroutine 11 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc0424d1d28 sp=0xc0424d1d20 pc=0x4525d0
runtime.mallocgc(0x991b6fc5, 0x7f9f40, 0x1, 0xc042016300)
        /usr/local/go/src/runtime/malloc.go:720 +0x8e1 fp=0xc0424d1dc8 sp=0xc0424d1d28 pc=0x410551
runtime.makeslice(0x7f9f40, 0x991b6fc5, 0x991b6fc5, 0x0, 0x0, 0x66be35)
        /usr/local/go/src/runtime/slice.go:61 +0x7e fp=0xc0424d1df8 sp=0xc0424d1dc8 pc=0x43e2fe
github.com/schollz/croc/src.splitFile(0xc042016300, 0x17, 0x2, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/utils.go:60 +0x14b fp=0xc0424d1e90 sp=0xc0424d1df8 pc=0x76d70b
github.com/schollz/croc/src.(*Croc).getFilesReady(0xc0422fa000, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/files.go:139 +0x379 fp=0xc0424d1fc8 sp=0xc0424d1e90 pc=0x7664a9
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc0424d1fd0 sp=0xc0424d1fc8 pc=0x455031
created by github.com/schollz/croc/src.(*Croc).processState
        /home/zns/work/src/github.com/schollz/croc/src/client.go:282 +0xe1e

goroutine 1 [chan receive, 3 minutes]:
github.com/schollz/croc/src.(*Croc).Send(0xc04215e000, 0xc042060090, 0xf, 0xc04205eb80, 0x14, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/api.go:125 +0x632
main.send(0xc0420c8c60, 0xc04207f740, 0x7acce8)
        /home/zns/work/src/github.com/schollz/croc/main.go:113 +0x1a2
main.main.func1(0xc0420c8c60, 0xc0420c0800, 0xc0420c8c60)
        /home/zns/work/src/github.com/schollz/croc/main.go:44 +0x32
github.com/urfave/cli.HandleAction(0x806e00, 0x8bf018, 0xc0420c8c60, 0x0, 0xc0420c0840)
        /home/zns/work/src/github.com/urfave/cli/app.go:501 +0xcf
github.com/urfave/cli.Command.Run(0x89ed38, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8a3725, 0xb, 0x0, ...)
        /home/zns/work/src/github.com/urfave/cli/command.go:165 +0x484
github.com/urfave/cli.(*App).Run(0xc042158000, 0xc04205c080, 0x3, 0x4, 0x0, 0x0)
        /home/zns/work/src/github.com/urfave/cli/app.go:259 +0x6ef
main.main()
        /home/zns/work/src/github.com/schollz/croc/main.go:91 +0xb51

goroutine 18 [semacquire, 5 minutes]:
sync.runtime_notifyListWait(0xc04205c6d0, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0x119
sync.(*Cond).Wait(0xc04205c6c0)
        /usr/local/go/src/sync/cond.go:56 +0x87
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc0420cc000, 0x0)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x98
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc0420cc000)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x4b
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xa4

goroutine 19 [semacquire, 5 minutes]:
sync.runtime_notifyListWait(0xc04205c890, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0x119
sync.(*Cond).Wait(0xc04205c880)
        /usr/local/go/src/sync/cond.go:56 +0x87
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc0420cc120, 0x0)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x98
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc0420cc120)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x4b
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xa4

goroutine 20 [syscall, 5 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0xad
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 56 [IO wait]:
internal/poll.runtime_pollWait(0xdb0ea0, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420e6cc8, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0420e6b18, 0x8bef58, 0xc0420e6b00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).Read(0xc0420e6b00, 0xc04236f400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:484 +0x248
net.(*netFD).Read(0xc0420e6b00, 0xc04236f400, 0x400, 0x400, 0x389d56b88f5, 0xb0cc00, 0x0)
        /usr/local/go/src/net/fd_windows.go:151 +0x56
net.(*conn).Read(0xc0422f4160, 0xc04236f400, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x71
github.com/schollz/croc/src.receiveMessage(0x8fb760, 0xc0422f4160, 0x8fb760, 0xc0422f4160, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:151 +0x1b4
github.com/schollz/croc/src.(*Croc).clientCommuncation(0xc04215e0f0, 0x89ef55, 0x5, 0x8fb760, 0xc0422f4160, 0x8bb2c97000, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:60 +0x9d
github.com/schollz/croc/src.(*Croc).listener.func1(0xc04215e0f0, 0x89ef55, 0x5, 0x8fb760, 0xc0422f4160)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:44 +0x6d
created by github.com/schollz/croc/src.(*Croc).listener
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:43 +0x182

goroutine 22 [semacquire, 5 minutes]:
sync.runtime_notifyListWait(0xc04215b4d0, 0x0)
        /usr/local/go/src/runtime/sema.go:510 +0x119
sync.(*Cond).Wait(0xc04215b4c0)
        /usr/local/go/src/sync/cond.go:56 +0x87
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc0420cc480, 0x0)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0x98
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc0420cc480)
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x4b
created by github.com/cihub/seelog.NewAsyncLoopLogger
        /home/zns/work/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0xa4

goroutine 26 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0xdb08f0, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420e6a08, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0420e6858, 0x8bef58, 0xc042469840, 0x697dbb, 0xc04207c000)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).Read(0xc0420e6840, 0xc04246f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:484 +0x248
net.(*netFD).Read(0xc0420e6840, 0xc04246f000, 0x1000, 0x1000, 0x0, 0x519161, 0xc0422f2961)
        /usr/local/go/src/net/fd_windows.go:151 +0x56
net.(*conn).Read(0xc04218a0b0, 0xc04246f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x71
crypto/tls.(*block).readFromUntil(0xc0422ec720, 0xdb1408, 0xc04218a0b0, 0x5, 0xc04218a0b0, 0xc04207c000)
        /usr/local/go/src/crypto/tls/conn.go:493 +0x9d
crypto/tls.(*Conn).readRecord(0xc0420c6380, 0x8bf817, 0xc0420c64a0, 0xc04207e380)
        /usr/local/go/src/crypto/tls/conn.go:595 +0xe7
crypto/tls.(*Conn).Read(0xc0420c6380, 0xc042491000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1156 +0x107
bufio.(*Reader).fill(0xc0420c0660)
        /usr/local/go/src/bufio/bufio.go:100 +0x125
bufio.(*Reader).Peek(0xc0420c0660, 0x2, 0x767f36, 0x0, 0xc0422f2600, 0x363, 0x5ef)
        /usr/local/go/src/bufio/bufio.go:132 +0x41
github.com/gorilla/websocket.(*Conn).read(0xc0420628c0, 0x2, 0x4, 0x3, 0xc042026570, 0xc042026500, 0xc04205cf58)
        /home/zns/work/src/github.com/gorilla/websocket/conn_read.go:12 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0420628c0, 0x0, 0x0, 0x1f0)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:779 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc0420628c0, 0x8f4f40, 0xc042178f90, 0xc042469d48, 0xc042469d68, 0x4107ff)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:939 +0xaa
github.com/gorilla/websocket.(*Conn).ReadJSON(0xc0420628c0, 0x816cc0, 0xc042292600, 0x0, 0xc042090900)
        /home/zns/work/src/github.com/gorilla/websocket/json.go:50 +0x36
github.com/schollz/croc/src.(*Croc).client.func1(0xc042486060, 0xc0420628c0, 0xc04215e000)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:74 +0xb2
created by github.com/schollz/croc/src.(*Croc).client
        /home/zns/work/src/github.com/schollz/croc/src/client.go:70 +0x6b3

goroutine 5 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc042060e8c)
        /usr/local/go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc042060e80)
        /usr/local/go/src/sync/waitgroup.go:129 +0x79
github.com/schollz/croc/src.(*Croc).client(0xc0422fa000, 0x0, 0xc04205eb80, 0x3, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:141 +0xa49
github.com/schollz/croc/src.(*Croc).Send.func2(0xc04215e000, 0xc04205eb80, 0x14, 0xc04205eb80, 0x3, 0xc0420dcfc0)
        /home/zns/work/src/github.com/schollz/croc/src/api.go:108 +0x33d
created by github.com/schollz/croc/src.(*Croc).Send
        /home/zns/work/src/github.com/schollz/croc/src/api.go:79 +0x5c1

goroutine 6 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc04219a47c)
        /usr/local/go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc04219a470)
        /usr/local/go/src/sync/waitgroup.go:129 +0x79
github.com/schollz/croc/src.(*Croc).client(0xc04215e000, 0x0, 0xc04205eb80, 0x3, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:141 +0xa49
github.com/schollz/croc/src.(*Croc).Send.func3(0xc04215e000, 0xc04205eb80, 0x3, 0xc0420dcfc0)
        /home/zns/work/src/github.com/schollz/croc/src/api.go:119 +0x65
created by github.com/schollz/croc/src.(*Croc).Send
        /home/zns/work/src/github.com/schollz/croc/src/api.go:114 +0x604

goroutine 50 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc0422fc7ac)
        /usr/local/go/src/runtime/sema.go:56 +0x40
sync.(*WaitGroup).Wait(0xc0422fc7a0)
        /usr/local/go/src/sync/waitgroup.go:129 +0x79
github.com/schollz/croc/src.(*Croc).startRelay(0xc04215e0f0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:27 +0xe5
created by github.com/schollz/croc/src.(*Croc).Send.func2
        /home/zns/work/src/github.com/schollz/croc/src/api.go:86 +0xfe

goroutine 51 [IO wait]:
internal/poll.runtime_pollWait(0xdb0c30, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0422c8488, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0422c82d8, 0xc042002ac0, 0x1, 0x0, 0x168)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).acceptOne(0xc0422c82c0, 0x168, 0xc0421142a0, 0x2, 0x2, 0xc0422c82d8, 0x4761a9, 0xc04222dc60, 0x4107ff, 0x10)
        /usr/local/go/src/internal/poll/fd_windows.go:793 +0xae
internal/poll.(*FD).Accept(0xc0422c82c0, 0xc0420555d0, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/internal/poll/fd_windows.go:827 +0x142
net.(*netFD).accept(0xc0422c82c0, 0xc042058f80, 0xc04222ddd0, 0x4022f8)
        /usr/local/go/src/net/fd_windows.go:192 +0x86
net.(*TCPListener).accept(0xc042004028, 0xc04222de00, 0x40119e, 0xc042058f80)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).AcceptTCP(0xc042004028, 0xc04222de48, 0xc04222de50, 0x18)
        /usr/local/go/src/net/tcpsock.go:246 +0x50
net/http.tcpKeepAliveListener.Accept(0xc042004028, 0x8bf198, 0xc042058f00, 0x8f9840, 0xc04215c300)
        /usr/local/go/src/net/http/server.go:3216 +0x36
net/http.(*Server).Serve(0xc0420649c0, 0x8f9580, 0xc042004028, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2770 +0x1ac
net/http.(*Server).ListenAndServe(0xc0420649c0, 0xc0420649c0, 0x5)
        /usr/local/go/src/net/http/server.go:2711 +0xb0
net/http.ListenAndServe(0xc04219a4c6, 0x5, 0x0, 0x0, 0x4, 0xc04219a4c6)
        /usr/local/go/src/net/http/server.go:2969 +0x81
github.com/schollz/croc/src.(*Croc).startServer(0xc04215e0f0, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/server.go:81 +0x1b4
created by github.com/schollz/croc/src.(*Croc).Send.func2
        /home/zns/work/src/github.com/schollz/croc/src/api.go:87 +0x120

goroutine 39 [IO wait]:
internal/poll.runtime_pollWait(0xdb0d00, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc042310488, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0423102d8, 0xc042002aa0, 0x1, 0x0, 0x510)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).acceptOne(0xc0423102c0, 0x510, 0xc0421141c0, 0x2, 0x2, 0xc0423102d8, 0xc04217a740, 0xc042237d30, 0x4107ff, 0x10)
        /usr/local/go/src/internal/poll/fd_windows.go:793 +0xae
internal/poll.(*FD).Accept(0xc0423102c0, 0xc0420555c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/internal/poll/fd_windows.go:827 +0x142
net.(*netFD).accept(0xc0423102c0, 0xc0420cc480, 0x8bf808, 0x8f4f40)
        /usr/local/go/src/net/fd_windows.go:192 +0x86
net.(*TCPListener).accept(0xc04218a088, 0x451cd0, 0xc042237ee0, 0xc042237ee8)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc04218a088, 0x8bee68, 0xc04215e0f0, 0x89ef55, 0x5)
        /usr/local/go/src/net/tcpsock.go:259 +0x50
github.com/schollz/croc/src.(*Croc).listener(0xc04215e0f0, 0x89ef55, 0x5, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:38 +0x196
github.com/schollz/croc/src.(*Croc).startRelay.func1(0xc04215e0f0, 0x89ef55, 0x5, 0xc0422fc7a0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:21 +0x114
created by github.com/schollz/croc/src.(*Croc).startRelay
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:18 +0xbc

goroutine 40 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0xdb0b60, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420e61c8, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0420e6018, 0xc042113480, 0x1, 0x0, 0x258)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).acceptOne(0xc0420e6000, 0x258, 0xc0421140e0, 0x2, 0x2, 0xc0420e6018, 0xc0422f40c0, 0xc042239d30, 0x4107ff, 0x10)
        /usr/local/go/src/internal/poll/fd_windows.go:793 +0xae
internal/poll.(*FD).Accept(0xc0420e6000, 0xc0422c6460, 0x0, 0x0, 0x0, 0x0, 0xc000000000, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/internal/poll/fd_windows.go:827 +0x142
net.(*netFD).accept(0xc0420e6000, 0x0, 0xc0422c6450, 0x1)
        /usr/local/go/src/net/fd_windows.go:192 +0x86
net.(*TCPListener).accept(0xc0422f40c0, 0x429f90, 0xc0423123a0, 0xc042239ee8)
        /usr/local/go/src/net/tcpsock_posix.go:136 +0x35
net.(*TCPListener).Accept(0xc0422f40c0, 0x8f8fe8, 0xc0422f40c0, 0xd, 0x8f8fc0)
        /usr/local/go/src/net/tcpsock.go:259 +0x50
github.com/schollz/croc/src.(*Croc).listener(0xc04215e0f0, 0x89ef5a, 0x5, 0x0, 0x0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:38 +0x196
github.com/schollz/croc/src.(*Croc).startRelay.func1(0xc04215e0f0, 0x89ef5a, 0x5, 0xc0422fc7a0)
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:21 +0x114
created by github.com/schollz/croc/src.(*Croc).startRelay
        /home/zns/work/src/github.com/schollz/croc/src/relay.go:18 +0xbc

goroutine 53 [sleep]:
time.Sleep(0xdf8475800)
        /usr/local/go/src/runtime/time.go:102 +0x17b
github.com/schollz/croc/src.(*Croc).channelCleanup(0xc04215e0f0)
        /home/zns/work/src/github.com/schollz/croc/src/server.go:289 +0x3ad
created by github.com/schollz/croc/src.(*Croc).startServer
        /home/zns/work/src/github.com/schollz/croc/src/server.go:19 +0x4a

goroutine 43 [runnable]:
time.Sleep(0x5f5e100)
        /usr/local/go/src/runtime/time.go:102 +0x17b
github.com/briandowns/spinner.(*Spinner).Start.func1(0xc042458000)
        /home/zns/work/src/github.com/briandowns/spinner/spinner.go:227 +0x61
created by github.com/briandowns/spinner.(*Spinner).Start
        /home/zns/work/src/github.com/briandowns/spinner/spinner.go:211 +0x62

goroutine 25 [select, 3 minutes]:
github.com/schollz/croc/src.(*Croc).client.func2(0xc042294120, 0xc0420c0000, 0xc0422fa000, 0xc042062280, 0xc0422c6680, 0xc042060e80)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:111 +0x103
created by github.com/schollz/croc/src.(*Croc).client
        /home/zns/work/src/github.com/schollz/croc/src/client.go:108 +0xa38

goroutine 55 [IO wait]:
internal/poll.runtime_pollWait(0xdb09c0, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc04246c1c8, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc04246c018, 0x8bef58, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).Read(0xc04246c000, 0xc04247c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:484 +0x248
net.(*netFD).Read(0xc04246c000, 0xc04247c000, 0x1000, 0x1000, 0xc042292200, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:151 +0x56
net.(*conn).Read(0xc042080088, 0xc04247c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x71
bufio.(*Reader).fill(0xc04204a0c0)
        /usr/local/go/src/bufio/bufio.go:100 +0x125
bufio.(*Reader).Peek(0xc04204a0c0, 0x2, 0x14, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0x41
github.com/gorilla/websocket.(*Conn).read(0xc042492000, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/zns/work/src/github.com/gorilla/websocket/conn_read.go:12 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc042492000, 0x0, 0x0, 0x1f0)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:779 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc042492000, 0x8f4f60, 0xc042434220, 0xc0424655d8, 0xc0424655f8, 0x4107ff)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:939 +0xaa
github.com/gorilla/websocket.(*Conn).ReadJSON(0xc042492000, 0x816cc0, 0xc04247aa00, 0xc0422fc040, 0x3)
        /home/zns/work/src/github.com/gorilla/websocket/json.go:50 +0x36
github.com/schollz/croc/src.(*Croc).startServer.func1(0x8f91c0, 0xc0421460e0, 0xc04247e000)
        /home/zns/work/src/github.com/schollz/croc/src/server.go:59 +0x719
net/http.HandlerFunc.ServeHTTP(0xc0422f83e0, 0x8f91c0, 0xc0421460e0, 0xc04247e000)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb0c7e0, 0x8f91c0, 0xc0421460e0, 0xc04247e000)
        /usr/local/go/src/net/http/server.go:2337 +0x137
net/http.serverHandler.ServeHTTP(0xc0420649c0, 0x8f91c0, 0xc0421460e0, 0xc04247e000)
        /usr/local/go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc0421760a0, 0x8f9780, 0xc0420da6c0)
        /usr/local/go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x282

goroutine 42 [semacquire]:
sync.runtime_SemacquireMutex(0xc0422fa0ac, 0x0)
        /usr/local/go/src/runtime/sema.go:71 +0x44
sync.(*Mutex).Lock(0xc0422fa0a8)
        /usr/local/go/src/sync/mutex.go:134 +0x10f
sync.(*RWMutex).Lock(0xc0422fa0a8)
        /usr/local/go/src/sync/rwmutex.go:93 +0x34
github.com/schollz/croc/src.(*Croc).processState(0xc0422fa000, 0x0, 0x0, 0x0, 0xc04246a5a0, 0x0, 0xc0420da400, 0x2, 0x4, 0xc04217294c, ...)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:189 +0x66
github.com/schollz/croc/src.(*Croc).client.func1(0xc042294120, 0xc042062280, 0xc0422fa000)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:80 +0x1d1
created by github.com/schollz/croc/src.(*Croc).client
        /home/zns/work/src/github.com/schollz/croc/src/client.go:70 +0x6b3

goroutine 27 [select, 3 minutes]:
github.com/schollz/croc/src.(*Croc).client.func2(0xc042486060, 0xc0420dd020, 0xc04215e000, 0xc0420628c0, 0xc042338010, 0xc04219a470)
        /home/zns/work/src/github.com/schollz/croc/src/client.go:111 +0x103
created by github.com/schollz/croc/src.(*Croc).client
        /home/zns/work/src/github.com/schollz/croc/src/client.go:108 +0xa38

goroutine 57 [IO wait]:
internal/poll.runtime_pollWait(0xdb0dd0, 0x72, 0x8f64c0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc0420e6f88, 0x72, 0xaca400, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xa2
internal/poll.(*ioSrv).ExecIO(0xb0a8d8, 0xc0420e6dd8, 0x8bef58, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:223 +0x13a
internal/poll.(*FD).Read(0xc0420e6dc0, 0xc042370000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:484 +0x248
net.(*netFD).Read(0xc0420e6dc0, 0xc042370000, 0x1000, 0x1000, 0xc042292200, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:151 +0x56
net.(*conn).Read(0xc0422f4168, 0xc042370000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x71
bufio.(*Reader).fill(0xc042152c60)
        /usr/local/go/src/bufio/bufio.go:100 +0x125
bufio.(*Reader).Peek(0xc042152c60, 0x2, 0x14, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0x41
github.com/gorilla/websocket.(*Conn).read(0xc042062640, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/zns/work/src/github.com/gorilla/websocket/conn_read.go:12 +0x47
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc042062640, 0x0, 0x0, 0x1f0)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:779 +0x63
github.com/gorilla/websocket.(*Conn).NextReader(0xc042062640, 0x8f4f60, 0xc042246a40, 0xc0424695d8, 0xc0424695f8, 0x4107ff)
        /home/zns/work/src/github.com/gorilla/websocket/conn.go:939 +0xaa
github.com/gorilla/websocket.(*Conn).ReadJSON(0xc042062640, 0x816cc0, 0xc04245e400, 0xc042172f80, 0x3)
        /home/zns/work/src/github.com/gorilla/websocket/json.go:50 +0x36
github.com/schollz/croc/src.(*Croc).startServer.func1(0x8f91c0, 0xc0421461c0, 0xc04247e100)
        /home/zns/work/src/github.com/schollz/croc/src/server.go:59 +0x719
net/http.HandlerFunc.ServeHTTP(0xc0422f83e0, 0x8f91c0, 0xc0421461c0, 0xc04247e100)
        /usr/local/go/src/net/http/server.go:1947 +0x4b
net/http.(*ServeMux).ServeHTTP(0xb0c7e0, 0x8f91c0, 0xc0421461c0, 0xc04247e100)
        /usr/local/go/src/net/http/server.go:2337 +0x137
net/http.serverHandler.ServeHTTP(0xc0420649c0, 0x8f91c0, 0xc0421461c0, 0xc04247e100)
        /usr/local/go/src/net/http/server.go:2694 +0xc3
net/http.(*conn).serve(0xc042058f00, 0x8f9780, 0xc0420dab80)
        /usr/local/go/src/net/http/server.go:1830 +0x658
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2795 +0x282
```

**Comment by sgon00** [comment]
Btw, I feel bad to use the word `folder`, I am not sure why that is the word comes out from my mind when I posted this issue. It should be "directory".

**Comment by schollz** [comment]
@sgon00 My first thought is that you ran out of disk space. How much disk space did you have on your computer when you tried sending the file?

The 5.1GB file will be split into several files, essentially adding another 5.1GB file to your disk (which is removed after transfer and should be removed on errors like this).

There is not a good way around this yet because big files cannot be loaded into memory - so the only other option is to stream them / save them to disk temporarily. And I don't know how to stream multiple pieces of a file simultaneously (yet) so I'm currently saving to the disk.

**Comment by sgon00** [comment]
@schollz Thank you very much for your investigation. My Windows 10 PC has about 20GB free space. Thus I think it's not ran out of disk space. 
Another weird thing is that the directory size is actually not 5.1GB. Right now, I have cut the entire directory from Windows to my Linux through samba, thus I can't be sure how much size it was in Windows. But the size in Linux with `du -sh` shows `6.4GB` now. I remembered it showed about 7GB in Windows, but my memory might be wrong. Since it's too big, I don't want to transfer it to my Windows PC again to only check the size again. Thanks.
